#!/bin/bash
# Dev-Stack Orchestrator - Report Generation Script
# Runs on Stop hook to generate final execution report

set -e

PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-.}"
CONTEXT_DIR="$PLUGIN_ROOT/context"
REPORTS_DIR="$PLUGIN_ROOT/reports"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
DATE_STAMP=$(date +"%Y%m%d_%H%M%S")
REPORT_FILE="$REPORTS_DIR/report_$DATE_STAMP.md"

# Ensure reports directory exists
mkdir -p "$REPORTS_DIR"

# Function to read JSON value safely
read_json() {
    local file="$1"
    local key="$2"
    local default="$3"
    
    if [ -f "$file" ] && command -v jq &> /dev/null; then
        jq -r "$key // \"$default\"" "$file" 2>/dev/null || echo "$default"
    else
        echo "$default"
    fi
}

# Read session state if available
SESSION_FILE="$CONTEXT_DIR/session-state.json"
TRACKING_FILE="$CONTEXT_DIR/agent-tracking.log"

TASK=$(read_json "$SESSION_FILE" '.task' 'Unknown')
PHASE=$(read_json "$SESSION_FILE" '.phase' 'Unknown')
STATUS=$(read_json "$SESSION_FILE" '.status' 'Unknown')
WORKERS_SPAWNED=$(read_json "$SESSION_FILE" '.workers.spawned' '0')
WORKERS_COMPLETED=$(read_json "$SESSION_FILE" '.workers.completed' '0')
WORKERS_FAILED=$(read_json "$SESSION_FILE" '.workers.failed' '0')
MCP_TOOLS=$(read_json "$SESSION_FILE" '.tool_usage.mcp_tools' '0')
FALLBACK_TOOLS=$(read_json "$SESSION_FILE" '.tool_usage.fallback_tools' '0')

# Generate report
cat > "$REPORT_FILE" << EOF
# Dev-Stack Execution Report

**Generated**: $TIMESTAMP
**Report ID**: $DATE_STAMP

---

## Summary

| Metric | Value |
|--------|-------|
| **Task** | $TASK |
| **Final Phase** | $PHASE |
| **Status** | $STATUS |
| **Workers Spawned** | $WORKERS_SPAWNED |
| **Workers Completed** | $WORKERS_COMPLETED |
| **Workers Failed** | $WORKERS_FAILED |

---

## Tool Usage Summary

| Tool Type | Count |
|-----------|-------|
| **MCP Tools Used** | $MCP_TOOLS |
| **Fallback Tools Used** | $FALLBACK_TOOLS |

EOF

# Calculate MCP usage percentage
TOTAL_TOOLS=$((MCP_TOOLS + FALLBACK_TOOLS))
if [ "$TOTAL_TOOLS" -gt 0 ]; then
    if command -v bc &> /dev/null; then
        MCP_PERCENT=$(echo "scale=1; $MCP_TOOLS * 100 / $TOTAL_TOOLS" | bc)
    else
        MCP_PERCENT=$((MCP_TOOLS * 100 / TOTAL_TOOLS))
    fi
    cat >> "$REPORT_FILE" << EOF
**MCP Tool Usage Rate**: ${MCP_PERCENT}%

EOF
    # Add warning if below target
    if [ "${MCP_PERCENT%.*}" -lt 90 ]; then
        cat >> "$REPORT_FILE" << EOF
> ⚠️ **Warning**: MCP tool usage below 90% target. Consider checking MCP server availability.

EOF
    fi
fi

# Add agent tracking summary if available
if [ -f "$TRACKING_FILE" ]; then
    cat >> "$REPORT_FILE" << EOF
---

## Agent Activity

EOF
    
    # Parse tracking log
    if grep -q "START" "$TRACKING_FILE" 2>/dev/null; then
        cat >> "$REPORT_FILE" << EOF
| Time | Event | Agent | Type | Scope |
|------|-------|-------|------|-------|
EOF
        # Format tracking entries
        grep -E "START|STOP" "$TRACKING_FILE" | while read -r line; do
            TIME=$(echo "$line" | awk -F'[][]' '{print $2}')
            EVENT=$(echo "$line" | awk -F'|' '{print $2}' | xargs)
            AGENT=$(echo "$line" | awk -F'|' '{print $3}' | sed 's/Agent: //' | xargs)
            TYPE=$(echo "$line" | awk -F'|' '{print $4}' | xargs)
            SCOPE=$(echo "$line" | awk -F'|' '{print $5}' | xargs)
            echo "| $TIME | $EVENT | $AGENT | $TYPE | $SCOPE |"
        done >> "$REPORT_FILE"
    fi
fi

# Add files modified section
FILES_MODIFIED=$(read_json "$SESSION_FILE" '.files_modified' '[]')
if [ "$FILES_MODIFIED" != "[]" ] && [ "$FILES_MODIFIED" != "" ]; then
    cat >> "$REPORT_FILE" << EOF

---

## Files Modified

\`\`\`json
$FILES_MODIFIED
\`\`\`

EOF
fi

# Add footer
cat >> "$REPORT_FILE" << EOF

---

## Recommendations

EOF

# Add recommendations based on report data
if [ "$WORKERS_FAILED" -gt 0 ]; then
    cat >> "$REPORT_FILE" << EOF
- Investigate failed workers to prevent future failures
EOF
fi

if [ "$FALLBACK_TOOLS" -gt 0 ] && [ "$TOTAL_TOOLS" -gt 0 ]; then
    if [ "${MCP_PERCENT%.*}" -lt 90 ]; then
        cat >> "$REPORT_FILE" << EOF
- Check MCP server availability to increase MCP tool usage
EOF
    fi
fi

if [ -z "$WORKERS_FAILED" ] || [ "$WORKERS_FAILED" = "0" ]; then
    cat >> "$REPORT_FILE" << EOF
- All workers completed successfully
EOF
fi

cat >> "$REPORT_FILE" << EOF

---

*Report generated by Dev-Stack Orchestrator v2.0.0*
EOF

# Output report location
echo "[Report] Generated: $REPORT_FILE"

# Also output a summary to stdout
echo ""
echo "=== Execution Summary ==="
echo "Task: $TASK"
echo "Status: $STATUS"
echo "Workers: $WORKERS_COMPLETED/$WORKERS_SPAWNED completed"
echo "MCP Tools: $MCP_TOOLS | Fallback: $FALLBACK_TOOLS"
echo "Report: $REPORT_FILE"
echo "========================"

# Cleanup temporary files
rm -f "$CONTEXT_DIR/agent-start-times.tmp" 2>/dev/null || true

exit 0
